sudo: false
language: node_js

node_js:
  - 8
  - 10

cache: yarn
script:
  - yarn lint
  - yarn test

deploy:
  - provider: script
    script: yarn deploy
    skip-cleanup: true
    on:
      branch: master
